// Generated by CoffeeScript 1.6.2
(function() {
  var gaussian, gaussianLib;

  gaussianLib = require("gaussian");

  gaussian = function(mean, variance) {
    var ret;

    ret = gaussianLib(mean, variance);
    ret.add = function(d) {
      return new gaussian(mean + d.mean, variance + d.variance);
    };
    ret.sub = function(d) {
      return new gaussian(mean - d.mean, variance + d.variance);
    };
    ret.scale = function(c) {
      return new gaussian(mean * c, variance * c * c);
    };
    return ret;
  };

  module.exports = gaussian;

}).call(this);
